verilog/core/syncflop.v
verilog/core/bytefifo.v
verilog/core/syncreg.v
verilog/core/adbg_pkg.sv
verilog/core/adbg_or1k_pkg.sv
verilog/core/adbg_or1k_status_reg.sv
verilog/core/adbg_or1k_module.sv
verilog/core/adbg_or1k_biu.sv
verilog/core/adbg_jsp_pkg.sv
verilog/core/adbg_jsp_module_core.sv
verilog/core/adbg_crc32.v
verilog/core/adbg_bus_module_core.sv
verilog/wb/adbg_wb_pkg.sv
verilog/wb/adbg_wb_biu.sv
verilog/wb/adbg_wb_module.sv
verilog/wb/adbg_jsp_wb_biu.sv
verilog/wb/adbg_jsp_wb_module.sv
verilog/wb/adbg_top_wb.sv

